name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: install golang migrate
      run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.0/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/migrate
          which migrate

    - name: Code checkout
      uses: actions/checkout@v2
      
    - name: Test
      env:
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: make test
