name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: install golang migrate
      run: |
        sudo curl -L https://packagecloud.io/golang-migrate/migrate/gpgkey | apt-key add -
        sudo echo "deb https://packagecloud.io/golang-migrate/migrate/ubuntu/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/migrate.list
        sudo apt-get update
        sudo apt-get install -y migrate

    - name: Test
      run: make test